# Generated by Django 4.1.7 on 2023-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=3000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    models.TextField(
                        default="https://99px.ru/sstorage/56/2015/01/image_560401151755269388068.jpg",
                        max_length=1000,
                        verbose_name="Image",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("other", "Other"),
                            ("jackets", "Jackets"),
                            ("shoes", "Shoes"),
                            ("jeans", "Jeans"),
                            ("shirts", "Shirts"),
                        ],
                        default="other",
                        max_length=100,
                        verbose_name="Category",
                    ),
                ),
                ("rest", models.PositiveIntegerField(verbose_name="Rest")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="Price"
                    ),
                ),
            ],
        ),
    ]
